[build]
  base = "public"
  command = "npm run build"  # Replace with the build command for your Express app
  publish = "public"  # Replace with the directory where your static files are generated

[context.production]
  command = "npm run start"  # Replace with the start command for your Express app
